import { SYNC_CONFIG } from './config';
import { KeyedBundle, Tombstones } from './engine';

const BASE = SYNC_CONFIG.url.replace(/\/$/, '');
const ANON = SYNC_CONFIG.anonKey;
const DEVICE_TABLE = 'devices';
const STATE_TABLE = 'sync_state';

function headers() {
  return {
    apikey: ANON,
    Authorization: `Bearer ${ANON}`,
    'Content-Type': 'application/json',
    Prefer: 'return=representation',
  };
}

async function req(path: string, opts: RequestInit = {}): Promise<Response> {
  const res = await fetch(`${BASE}/rest/v1${path}`, {
    ...opts,
    headers: { ...headers(), ...(opts.headers || {}) },
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`Supabase ${opts.method || 'GET'} ${path} failed ${res.status}: ${txt}`);
  }
  return res;
}

function deviceId(): string {
  // generated by the app at startup, passed in
  throw new Error('deviceId not set — call setDeviceId first');
}

let _deviceId = '';
export function setDeviceId(id: string) { _deviceId = id; }
export function getDeviceId() { return _deviceId; }

export async function registerDevice(name = 'device'): Promise<void> {
  await req(`/${DEVICE_TABLE}?id=eq.${_deviceId}`, {
    method: 'PATCH',
    body: JSON.stringify({ name, last_sync_at: new Date().toISOString() }),
  });
}

export async function pullRemote(): Promise<{ doc: KeyedBundle; lineage: Record<string, string>; tombstones: Tombstones; updatedAt: string } | null> {
  const res = await req(`/${STATE_TABLE}?id=eq.1&select=doc,lineage,tombstones,updated_at`);
  const rows = await res.json();
  if (!rows.length) return null;
  const r = rows[0];
  return {
    doc: r.doc ?? {},
    lineage: r.lineage ?? {},
    tombstones: r.tombstones ?? {},
    updatedAt: r.updated_at,
  };
}

export async function pushRemote(doc: KeyedBundle, lineage: Record<string, string>, tombstones: Tombstones): Promise<void> {
  const payload = {
    id: 1,
    doc,
    lineage,
    tombstones,
    updated_at: new Date().toISOString(),
    updated_by: _deviceId,
  };
  await req(`/${STATE_TABLE}?id=eq.1`, {
    method: 'PATCH',
    body: JSON.stringify(payload),
  });
}

export async function getRemoteUpdatedAt(): Promise<string | null> {
  const res = await req(`/${STATE_TABLE}?id=eq.1&select=updated_at`);
  const rows = await res.json();
  return rows[0]?.updated_at ?? null;
}